import type { Metadata } from "next";
import { CartProvider } from "../context/CartContext";
import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black">
        <div className="min-h-screen bg-[radial-gradient(closest-corner_at_top_right,#51596b,#0D1B2A)]">
          <CartProvider> {children}</CartProvider>
        </div>
      </body>
    </html>
  );
}
